//@ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY CONTENTS

export const PLUGIN_IMPORTS = {
  "ExampleDemoWebview": "../altv/plugins/[example]/demo/webview/index.astro",
  "ExampleDemo2Webview": "../altv/plugins/[example]/demo2/webview/index.astro"
};
